input.onButtonPressed(Button.A, function () {
    music.setTempo(50)
    basic.showString("e")
    music.playTone(659, music.beat(BeatFraction.Breve))
    basic.pause(2000)
    basic.showString("B")
    music.playTone(494, music.beat(BeatFraction.Breve))
    basic.pause(2000)
    basic.showString("G")
    music.playTone(392, music.beat(BeatFraction.Breve))
    basic.pause(2000)
    basic.showString("D")
    music.playTone(294, music.beat(BeatFraction.Breve))
    basic.pause(2000)
    basic.showString("A")
    music.playTone(220, music.beat(BeatFraction.Breve))
    basic.pause(2000)
    basic.showString("E")
    music.playTone(165, music.beat(BeatFraction.Breve))
    basic.clearScreen()
})
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    basic.showString("Accordatore gtr premi A")
})
basic.showString("Logo=info")
